### ISSUE TITLE
Upgrade sharp

### ISSUE THREAD

**Issue by lolmaus** [kaliber5/ember-responsive-image#51]
Using the old version of the `sharp` dependency breaks builds on Windows.

**Comment by simonihmig** [comment]
@lolmaus can you please provide a PR?

**Comment by lolmaus** [comment]
@simonihmig, `ember-responsive-image` has no lockfile. Should I check it in?

**Comment by simonihmig** [comment]
Yes! Also add `useYarn: true` here: https://github.com/kaliber5/ember-responsive-image/blob/master/config/ember-try.js#L12

**Comment by ghost** [comment]
This sharp upgrade is also needed for anyone using Node v12. Might you be able to release an update with that PR soon?

I saw this issue is affecting other projects: https://github.com/gatsbyjs/gatsby/issues/13780#issuecomment-488383193

**Comment by jasonmevans** [comment]
You guys want help with this? I'm blocked by the same, I believe.

**Comment by jasonmevans** [comment]
Quick update, I was able to work around my build issue with a `package.json` `resolution`,

```json
  "resolutions": {
    "sharp": "0.23.0"
  },
```

You must be on the latest RC, `v1.0.0-rc.6`, for everything to work, especially if you are also using `ember-lazy-responsive-image` since that's the version it depends on. Once the stars align things should work. 

As a side note, we use docker for our projects which makes debugging things like this tricky. This [stack overflow](https://stackoverflow.com/questions/26220957/how-can-i-inspect-the-file-system-of-a-failed-docker-build/35387446#35387446) did the trick for debugging my failed docker builds to solve my version mismatch problem.
